Remove neps argument 'searcher_path'-New loading design for optimizer
automl/neps pull request #105
Opened 2024-06-07 08:59 UTC by danrgll

2024-06-19 10:01 UTC, eddiebergman requested changes
Looks good as a far as I can see (hard to validate strings everywhere tbh)

One bug that needs fixing, rest is fine!

2024-06-19 10:03 UTC, eddiebergman commented
Seems like the test failures here were fixed by @karibbov in #ade69db7c23673fcbe9d2ac2b6dc348810b45bd0 , many thanks :)

2024-06-21 12:01 UTC, danrgll commented on docs/doc_yamls/full_configuration_template.yaml
> +    log: True
yeah i think both are interpreted as boolean, but we can definitely align with the more common usage

2024-06-21 13:25 UTC, danrgll commented on tests/test_neps_api/testing_scripts/user_yaml_neps.py
> +searcher_path = os.path.join(parent_directory, "testing_yaml/optimizer_test")
fixed [9406896](https://github.com/automl/neps/pull/105/commits/94068963440f83f7a39327ec67cc929fbcd68f66)

2024-06-21 13:25 UTC, merged